### ISSUE TITLE
objective-C Grammar

### ISSUE THREAD

**Issue by ericxu1983** [creekit/iOS_message_client#1]

**Comment by creekit** [comment]
@property(weak, nonatomic) BOOL completed;

## Q1:what does weak mean?

Note: The opposite to weak is strong. There’s no need to specify the strong attribute explicitly, because it is the default.

Local variables (and non-property instance variables) also maintain strong references to objects by default.

this means that  
 NSDate *originalDate = self.lastModificationDate;

is actually like C++ smart pointer(strong reference) or Java style instance, not like C style pointer any more.

---

If you don’t want a variable to maintain a strong reference, you can declare it as __weak, like this:

```
NSObject * __weak weakVariable;
```

To avoid a dangerous dangling pointer to the memory originally occupied by the now deallocated object, a weak reference is automatically set to nil when its object is deallocated.

---

```
NSObject * __weak someObject = [[NSObject alloc] init];
```

In this example, the newly allocated object has no strong references to it, so it is immediately deallocated and someObject is set to nil.

---

use strong reference to cache weak reference

---

traditional raw pointer:
    NSObject \* ___unsafe_unretained_ unsafeReference;

**Comment by creekit** [comment]
## Q2: is @synthesize still necessary?can i just omit it?

http://useyourloaf.com/blog/2012/08/01/property-synthesis-with-xcode-4-dot-4.html

simply put, 
@property String\* name;

the compiler would generate default codes below:
@synthesize name = _name;

so it means:
1. the instance variable name is "_name", not "name"
2. it generates 2 getter and setter methods, [obj name] && [obj setName:@"hello"]

**Comment by creekit** [comment]
NString\* str = @"this is a sentence";

## Q3: @"" means what? from C++ perspective.

http://stackoverflow.com/questions/8032375/difference-between-nsstring-literals

just like C language string literals, in rdata section in binary?

**Comment by creekit** [comment]
## Q1 deeper: property knowledge

@property (readonly, getter=isFinished) BOOL finished;

readonly means "attribute"
using "DOT Syntax" is better:
Setting a value using somePerson.firstName = @"Johnny"

**Comment by creekit** [comment]
## conclusion

ARC version OC just like Java, by default, 
1. obj *pObj is the strong reference, if you want to use the weak version, you need to declare weak version specifically. 
2. use property to encapsulate data most of the time
